repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v2.2.3
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml # Checks yaml files for parseable syntax.
          - id: check-json # Checks json files for parseable syntax.
          - id: check-added-large-files
          - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
          - id: check-merge-conflict # Check for files that contain merge conflict strings.
          - id: debug-statements # Check for debugger imports and py37+ `breakpoint()` calls in python source.
          - id: detect-private-key
          - id: mixed-line-ending
          - id: requirements-txt-fixer # Sorts entries in requirements.txt
    -   repo: https://github.com/psf/black
        rev: 23.10.1
        hooks:
        - id: black
    -   repo: https://github.com/pycqa/flake8
        rev: 4.0.1
        hooks:
        - id: flake8
        args: ['--config=./setup.cfg']
    -   repo: https://github.com/pycqa/isort
        rev: 5.12.0
        hooks:
        - id: isort
        name: isort (python)